# How do I use Travis-CI with C# or F# http://stackoverflow.com/q/16751772/637783
language: objective-c

env:
 matrix:
  - MONO_VERSION="3.4.0"

before_install:
 - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
 - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

script:
 - ./build.fsx Test
