#Appveyor http://www.appveyor.com/docs/appveyor-yml

os: Windows Server 2012

build_script:
  - "set PATH=%PATH%;C:\\Program Files (x86)\\Microsoft SDKs\\F#\\3.1\\Framework\\v4.0\\"
  - fsi --exec build.fsx Build

test:
  assemblies:
    - "Src\\*Apis.Tests\\bin\\*Apis.Tests.dll"
    - "Src\\*Auth.Tests\\bin\\*Auth.Tests.dll"
